name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose up --build --abort-on-container-exit

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        env:
          ZEROBOUNCE_API_KEY: ${{ secrets.ZEROBOUNCE_API_KEY }}
          ZEROBOUNCE_HTTP_TIMEOUT: 3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/_output/coverage.xml
